// app/routes/app.analyze.jsx
import { useLoaderData, Link } from "react-router"; // CHANGED: proper import for V7
import { authenticate } from "../shopify.server";
import prisma from "../db.server";
import OpenAI from "openai";

export const loader = async ({ request }) => {
  const { session } = await authenticate.admin(request);
  const url = new URL(request.url);
  
  // 1. Get Data from URL parameters
  const productTitle = url.searchParams.get("product");
  const velocity = url.searchParams.get("velocity");
  const stock = url.searchParams.get("stock");

  // 2. Get the User's API Key
  const settings = await prisma.merchantSettings.findUnique({
    where: { shop: session.shop }
  });

  if (!settings?.openaiKey) {
    return { error: "NO_KEY" };
  }

  // 3. Call OpenAI
  try {
    const openai = new OpenAI({ apiKey: settings.openaiKey });
    
    const prompt = `
      Act as an Inventory Expert. 
      Product: "${productTitle}"
      Current Stock: ${stock} units
      Sales Rate: ${velocity} units/day.
      
      The user is worried about stock levels. 
      Provide 3 short, actionable bullet points on what they should do. 
      Keep it professional but urgent.
    `;

    const completion = await openai.chat.completions.create({
      messages: [{ role: "user", content: prompt }],
      model: "gpt-3.5-turbo",
    });

    return { 
      advice: completion.choices[0].message.content,
      productTitle 
    };

  } catch (err) {
    return { error: err.message };
  }
};

export default function Analyze() {
  const data = useLoaderData();

  return (
    <div style={{ padding: "40px", maxWidth: "800px", margin: "0 auto", fontFamily: "system-ui" }}>
      <Link to="/app" style={{ color: "#666", textDecoration: "none" }}>&larr; Back to Dashboard</Link>
      
      <div style={{ marginTop: "20px" }}>
        <h1>🤖 AI Analysis</h1>
        
        {data.error === "NO_KEY" ? (
          <div style={{ background: "#ffeeba", padding: "20px", borderRadius: "8px" }}>
            <h3>⚠️ Missing API Key</h3>
            <p>You haven't entered your OpenAI API Key yet.</p>
            <Link to="/app/settings" style={{ fontWeight: "bold" }}>Go to Settings</Link>
          </div>
        ) : data.error ? (
          <div style={{ color: "red" }}>Error: {data.error}</div>
        ) : (
          <div style={{ background: "white", padding: "30px", borderRadius: "8px", boxShadow: "0 4px 12px rgba(0,0,0,0.1)" }}>
            <h2 style={{ marginTop: 0 }}>Consultant Report: {data.productTitle}</h2>
            <div style={{ lineHeight: "1.6", whiteSpace: "pre-wrap" }}>
              {data.advice}
            </div>
            <div style={{ marginTop: "20px", paddingTop: "20px", borderTop: "1px solid #eee", fontSize: "0.9em", color: "#666" }}>
              *Generated by your custom AI Model*
            </div>
          </div>
        )}
      </div>
    </div>
  );
}